from __future__ import annotations

import json
from pathlib import Path

import typer
from rich import print

from oto_bot.agents.ceo import CEOAgent
from oto_bot.agents.registry import AgentRegistry
from oto_bot.analytics.scoring import composite_score
from oto_bot.backtest.engine import BacktestEngine
from oto_bot.core.models import Hypothesis
from oto_bot.experiments.ledger import ExperimentLedger
from oto_bot.governance.risk import RiskGate
from oto_bot.memory.manager import MemoryManager
from oto_bot.strategies.base import StrategyContext
from oto_bot.strategies.day_trader import DayTraderStrategy
from oto_bot.strategies.scalper import ScalperStrategy
from oto_bot.strategies.swing_trader import SwingTraderStrategy

app = typer.Typer(add_completion=False)


def _pick_strategy(name: str):
    normalized = name.lower()
    if normalized == "day":
        return DayTraderStrategy()
    if normalized == "swing":
        return SwingTraderStrategy()
    if normalized == "scalp":
        return ScalperStrategy()
    if normalized in ("scalp2", "scalp_v2"):
        from oto_bot.strategies.scalper_v2 import ScalperV2Strategy
        return ScalperV2Strategy()
    raise typer.BadParameter("strategy must be one of: day, swing, scalp, scalp2")


def _fetch_data(market: str, symbol: str, timeframe: str):
    """Try real data providers, fall back to synthetic."""
    try:
        from oto_bot.data.factory import DataProviderFactory
        provider = DataProviderFactory.get_provider(market)
        data = provider.fetch_ohlcv(symbol, timeframe, limit=500)
        if data is not None and len(data) >= 100:
            return data
    except Exception:
        pass
    from oto_bot.utils.data import make_synthetic_ohlc
    return make_synthetic_ohlc(500)


@app.command()
def bootstrap() -> None:
    """Initialize the lab: create directories, seed agents, setup database."""
    for folder in ["memories", "experiments", "artifacts", "logs"]:
        Path(folder).mkdir(parents=True, exist_ok=True)
    registry = AgentRegistry()
    created = registry.seed_defaults()
    MemoryManager()
    print(f"[green]Bootstrap complete.[/green] Seeded {len(created)} new agents.")
    print("[dim]Database initialized at artifacts/experiments.sqlite3[/dim]")


@app.command()
def cycle(
    market: str = "crypto",
    strategy: str = "day",
    symbol: str = "BTCUSDT",
    timeframe: str = "1h",
) -> None:
    """Run a single research cycle."""
    registry = AgentRegistry()
    registry.seed_defaults()
    memory = MemoryManager()
    ceo = CEOAgent(registry, memory_manager=memory)
    ledger = ExperimentLedger()
    risk_gate = RiskGate()
    engine = BacktestEngine()
    strategy_impl = _pick_strategy(strategy)

    ceo_profile = registry.find_by_name("Atlas CEO")
    hypothesis = Hypothesis(
        title=f"{strategy_impl.name}_{market}_{symbol}",
        thesis="Baseline automated hypothesis generated by CEO cycle.",
        market=market,
        strategy_family=strategy,
        timeframe=timeframe,
        invalidation="Risk-adjusted metrics fail promotion gates.",
        expected_edge="Trend or mean-reversion persistence.",
        author_agent_id=ceo_profile.agent_id if ceo_profile else "unknown",
    )
    memory.save_hypothesis(hypothesis)

    data = _fetch_data(market, symbol, timeframe)
    context = StrategyContext(market=market, strategy_family=strategy, symbol=symbol, timeframe=timeframe)
    result = engine.run(strategy_impl, data, context)

    risk_report = risk_gate.approve(result)
    result.promoted = result.promoted and risk_report.approved
    result.notes = f"{result.notes}; risk_gate={risk_report.summary}; composite_score={composite_score(result):.4f}"

    memory.save_result(result)
    decision = ceo.review_experiment(result)

    ledger.log({
        "hypothesis": hypothesis.title,
        "market": market,
        "strategy": strategy,
        "result": {k: v for k, v in result.__dict__.items() if k != "created_at"}
        | {"created_at": result.created_at.isoformat()},
        "decision": {k: v for k, v in decision.__dict__.items() if k != "created_at"}
        | {"created_at": decision.created_at.isoformat()},
    })
    print("[bold cyan]Cycle finished[/bold cyan]")
    print(json.dumps({
        "hypothesis": hypothesis.title,
        "roi": result.roi,
        "win_rate": result.win_rate,
        "profit_factor": result.profit_factor,
        "sharpe": result.sharpe,
        "sortino": result.sortino,
        "cagr": result.cagr,
        "max_drawdown": result.max_drawdown,
        "total_trades": result.total_trades,
        "regime": result.regime,
        "decision": decision.decision,
        "reasoning": decision.reasoning,
    }, indent=2))


@app.command()
def autonomous(
    markets: str = "crypto,forex",
    strategies: str = "day,swing,scalp",
    max_cycles: int = 50,
    pause: float = 1.0,
) -> None:
    """Run the autonomous 24/7 research loop."""
    from oto_bot.orchestrator import Orchestrator

    market_list = [m.strip() for m in markets.split(",")]
    strategy_list = [s.strip() for s in strategies.split(",")]

    orchestrator = Orchestrator(
        markets=market_list,
        strategies=strategy_list,
        cycle_pause_seconds=pause,
        max_cycles=max_cycles,
    )
    orchestrator.run_autonomous()


@app.command()
def brief() -> None:
    """Generate today's executive brief from the CEO."""
    registry = AgentRegistry()
    registry.seed_defaults()
    memory = MemoryManager()
    ceo = CEOAgent(registry, memory_manager=memory)
    report = ceo.generate_daily_brief()
    print(report)


@app.command()
def suggest() -> None:
    """Get CEO's suggested next experiments."""
    registry = AgentRegistry()
    registry.seed_defaults()
    memory = MemoryManager()
    ceo = CEOAgent(registry, memory_manager=memory)
    suggestions = ceo.suggest_next_experiments()
    print(json.dumps(suggestions, indent=2))


@app.command()
def dashboard() -> None:
    """Show the strategy comparison dashboard."""
    from rich.table import Table
    from rich.console import Console

    memory = MemoryManager()
    recent = memory.get_recent_results(n=50)
    if not recent:
        print("[dim]No experiments found. Run some cycles first.[/dim]")
        return

    console = Console()
    table = Table(title="Experiment Dashboard", show_header=True, header_style="bold magenta")
    table.add_column("#", style="dim", width=4)
    table.add_column("Strategy", style="cyan", max_width=35)
    table.add_column("Market")
    table.add_column("Sharpe", justify="right")
    table.add_column("Sortino", justify="right")
    table.add_column("ROI", justify="right")
    table.add_column("WR", justify="right")
    table.add_column("Max DD", justify="right", style="red")
    table.add_column("Trades", justify="right")
    table.add_column("Status", justify="center")

    for i, row in enumerate(recent[:20], 1):
        d = row["data"]
        cat = row.get("category", "")
        status = "[green]PROMO[/green]" if cat == "promotion" else "[yellow]HOLD[/yellow]"
        table.add_row(
            str(i),
            str(d.get("hypothesis_title", ""))[:35],
            str(d.get("market", "")),
            f"{d.get('sharpe', 0):.2f}",
            f"{d.get('sortino', 0):.2f}",
            f"{d.get('roi', 0):.1%}",
            f"{d.get('win_rate', 0):.1%}",
            f"{d.get('max_drawdown', 0):.1%}",
            str(d.get("total_trades", 0)),
            status,
        )
    console.print(table)


@app.command()
def campaign_scalper(
    max_experiments: int = 200,
    capital: float = 10_000.0,
    max_leverage: float = 5.0,
) -> None:
    """Launch full scalper research campaign — CEO + all agents."""
    from oto_bot.campaigns.scalper_research import ScalperResearchCampaign

    campaign = ScalperResearchCampaign(
        max_experiments=max_experiments,
        initial_capital=capital,
        max_leverage=max_leverage,
    )
    campaign.run()


@app.command()
def evolve(
    capital: float = 10_000.0,
    population: int = 30,
    generations: int = 100,
    target_roi: float = 0.50,
) -> None:
    """Run overnight evolutionary scalper optimization. RESEARCH ONLY."""
    from oto_bot.campaigns.overnight_scalper import OvernightEvolver

    evolver = OvernightEvolver(
        capital=capital,
        population_size=population,
        max_generations=generations,
        target_roi=target_roi,
    )
    evolver.run()


@app.command()
def hire(name: str, role: str, department: str, mandate: str) -> None:
    """Hire a new specialist agent."""
    registry = AgentRegistry()
    registry.seed_defaults()
    ceo = CEOAgent(registry)
    profile = ceo.hire_agent(name=name, role=role, department=department, mandate=mandate)
    print(f"[green]Hired[/green] {profile.name} ({profile.role})")


@app.command()
def fire(name: str) -> None:
    """Retire an agent."""
    registry = AgentRegistry()
    registry.seed_defaults()
    ceo = CEOAgent(registry)
    ok = ceo.fire_agent(name)
    if ok:
        print(f"[yellow]Retired[/yellow] {name}")
    else:
        print(f"[red]Agent not found:[/red] {name}")


if __name__ == "__main__":
    app()
